/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to standardize the environment
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Global Test Configuration
// This ensures all tests (unit, integration, etc.) run fast and provide clear logs.
tasks.withType<Test>().configureEach {
    // 1. Performance: Run tests in parallel to reduce feedback time
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).coerceAtLeast(1)

    // 2. Observability: Show exactly what passed/failed in the console
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true // Shows println() from inside tests
    }
}